### ISSUE TITLE
install postgis

### ISSUE THREAD

**Issue by hopewise** [tutumcloud/postgresql#5]
Hi!,

As this is a dedicated image for postgresql, its important to support postgis extension, or at least to make it optional..

**Comment by jifeon** [comment]
Hi! In our project we used this image as base and install all custom extensions in our own docker repo. BTW official postgres image seems to me more useful for these purposes because they have entrypoint directory .

**Comment by hopewise** [comment]
Thanks, I am currently using mdillon/postgis which is based on postgres:9.2
